### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Not in range 0..15, inclusive: 16

### ISSUE THREAD

**Issue by rainmeterLotus** [nervouself/color_thief_flutter#1]
E/flutter (14527): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Not in range 0..15, inclusive: 16
E/flutter (14527): #0      List.[] (dart:core-patch/growable_array.dart:149:60)
E/flutter (14527): #1      _medianCutApply.doCut (package:quantize_dart/quantize_dart.dart:428:30)
E/flutter (14527): #2      _medianCutApply (package:quantize_dart/quantize_dart.dart:456:67)
E/flutter (14527): #3      quantize.iter (package:quantize_dart/quantize_dart.dart:502:20)
E/flutter (14527): #4      quantize (package:quantize_dart/quantize_dart.dart:519:7)
E/flutter (14527): #5      getPaletteFromImage

**Comment by BeMacized** [comment]
Running into a similar error:

```
E/flutter ( 6149): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Not in range 0..21, inclusive: 22
E/flutter ( 6149): #0      List.[] (dart:core-patch/growable_array.dart:149:60)
E/flutter ( 6149): #1      _medianCutApply.doCut (package:quantize_dart/quantize_dart.dart:428:30)
E/flutter ( 6149): #2      _medianCutApply (package:quantize_dart/quantize_dart.dart:456:54)
E/flutter ( 6149): #3      quantize.iter (package:quantize_dart/quantize_dart.dart:502:20)
E/flutter ( 6149): #4      quantize (package:quantize_dart/quantize_dart.dart:529:7)
E/flutter ( 6149): #5      getPaletteFromImage (package:color_thief_flutter/color_thief_flutter.dart:89:16)
```

**Comment by jzsn2018** [comment]
> Running into a similar error:
> 
> ```
> E/flutter ( 6149): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Not in range 0..21, inclusive: 22
> E/flutter ( 6149): #0      List.[] (dart:core-patch/growable_array.dart:149:60)
> E/flutter ( 6149): #1      _medianCutApply.doCut (package:quantize_dart/quantize_dart.dart:428:30)
> E/flutter ( 6149): #2      _medianCutApply (package:quantize_dart/quantize_dart.dart:456:54)
> E/flutter ( 6149): #3      quantize.iter (package:quantize_dart/quantize_dart.dart:502:20)
> E/flutter ( 6149): #4      quantize (package:quantize_dart/quantize_dart.dart:529:7)
> E/flutter ( 6149): #5      getPaletteFromImage (package:color_thief_flutter/color_thief_flutter.dart:89:16)
> ```

Me too

**Comment by nervouself** [comment]
Can you provide more information? Like your os or your platform or the list/picture?

**Comment by nervouself** [comment]
@BeMacized @yinxiaorong @rainmeterLotus 
You can install the latest version `1.0.1` to check if it is resolved.
