### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Not in range 0..2, inclusive: -1

### ISSUE THREAD

**Issue by ra-develop** [nervouself/color_thief_flutter#2]
Error of determination of black color (RGB [0,0,0])

Console output:
E/flutter ( 7332): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Not in range 0..2, inclusive: -1
E/flutter ( 7332): #0      List.[] (dart:core-patch/growable_array.dart:149:60)
E/flutter ( 7332): #1      _safeGetArray (package:quantize_dart/quantize_dart.dart:320:14)
E/flutter ( 7332): #2      _medianCutApply.doCut (package:quantize_dart/quantize_dart.dart:438:52)
E/flutter ( 7332): #3      _medianCutApply (package:quantize_dart/quantize_dart.dart:464:67)
E/flutter ( 7332): #4      quantize.iter (package:quantize_dart/quantize_dart.dart:510:20)
E/flutter ( 7332): #5      quantize (package:quantize_dart/quantize_dart.dart:527:7)
E/flutter ( 7332): #6      getPaletteFromImage (package:color_thief_flutter/color_thief_flutter.dart:88:18)
E/flutter ( 7332): <asynchronous suspension>
E/flutter ( 7332): #7      getColorFromImage (package:color_thief_flutter/color_thief_flutter.dart:113:25)
E/flutter ( 7332): #8      getColorFromUrl (package:color_thief_flutter/color_thief_flutter.dart:128:31)

Debug Variables:
 _emptyList = {_List} size = 0
exception = {RangeError} RangeError (index): Invalid value: Not in range 0..2, inclusive: -1
 _hasValue = true
 _stackTrace = null
 end = 2
 invalidValue = -1
 message = "Invalid value"
 name = "index"
 start = 0
index = -1
this = {_GrowableList} size = 3
 0 = 938
 1 = 938
 2 = 938

**Comment by ra-develop** [comment]
File for test
![imgpsh_fullsize_anim2](https://user-images.githubusercontent.com/52385216/72549374-db111f80-3890-11ea-8a55-0eb64ecf5e09.png)

**Comment by nervouself** [comment]
Thanks! I'm working on it.

**Comment by nervouself** [comment]
@ra-develop 
I'm trying to reproduce the error by the file your sharing, but it works fine 🤔. The output is [4,4,4] and in line with expectations.
But I resolved the out of range error, you can update to 1.0.2 and try it again.

**Comment by ra-develop** [comment]
Thank you! After update to new version it is worked. Good luck!

**Comment by nervouself** [comment]
✌
